
module OnionData exposing (..)


type Source = TheOnion | NotTheOnion

posts = [ { title = "'No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1820163660?utm_content=Main&utm_campaign=SF&utm_source=Twitter&utm_medium=SocialMarketing", source = TheOnion }
        , { title = "Trump Warns Removing Confederate Statues Could Be Slippery Slope To Eliminating Racism Entirely", url = "https://politics.theonion.com/trump-warns-removing-confederate-statues-could-be-slipp-1819592904", source = TheOnion }
        , { title = "‘No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1819580358", source = TheOnion }
        , { title = "Roy Moore Retires From Politics To Spend More Quality Time With Someone's Kid", url = "https://politics.theonion.com/roy-moore-retires-from-politics-to-spend-more-quality-t-1821235915", source = TheOnion }
        , { title = "Mike Pence Disappointed In The 200,000 Husbands And Fathers Who Permitted Women To Attend March", url = "http://www.theonion.com/article/mike-pence-disappointed-200000-husbands-and-father-55116?utm_medium=RSS&utm_campaign=feeds", source = TheOnion }
        , { title = "Mike Pence Disappointed God Has Never Asked Him To Kill One Of Own Children", url = "http://www.theonion.com/article/mike-pence-disappointed-god-has-never-asked-him-ki-55239?utm_medium=RSS&utm_campaign=feeds", source = TheOnion }
        , { title = "Logan Paul: 'I Didn’t Realize People Who Commit Suicide Kill Themselves'", url = "https://www.theonion.com/logan-paul-i-didn-t-realize-people-who-commit-suicide-1822460035", source = TheOnion }
        , { title = "RNC: 'We Warned You Gay Marriage Would Be A Slippery Slope Toward Accepting Pedophilia'", url = "https://politics.theonion.com/rnc-we-warned-you-gay-marriage-would-be-a-slippery-slo-1821095609", source = TheOnion }
        , { title = "‘No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "http://www.theonion.com/article/no-way-prevent-says-only-nation-where-regularly-ha-51444?utm_source=Twitter&utm_medium=SocialMarketing&utm_campaign=Pic:1:Default", source = TheOnion }
        , { title = "Paul Ryan Confident American People Will Warm Up To Tax Plan Once They Realize Life A Cruel And Meaningless Farce", url = "https://politics.theonion.com/paul-ryan-confident-american-people-will-warm-up-to-tax-1821509050", source = TheOnion }
        , { title = "Panicked Donald Trump Jr. Tries To Cover Up Contact With WikiLeaks By Deleting Firefox Icon From Desktop", url = "https://politics.theonion.com/panicked-donald-trump-jr-tries-to-cover-up-contact-wit-1821133627", source = TheOnion }
        , { title = "Political Scientists Baffled By Trump’s Ability To End Something He Had No Control Over Just Days Ago", url = "https://politics.theonion.com/political-scientists-baffled-by-trump-s-ability-to-end-1827000942", source = TheOnion }
        , { title = "Gay Conversion Therapists Claim Most Patients Fully Straight By The Time They Commit Suicide", url = "https://www.theonion.com/gay-conversion-therapists-claim-most-patients-fully-str-1819577679", source = TheOnion }
        , { title = "”No way to prevent this” says only nations where this regualrly happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1820163660?utm_content=Main&utm_campaign=SF&utm_source=Twitter&utm_medium=SocialMarketing", source = TheOnion }
        , { title = "‘Nothing Is More Attractive Than Confidence,’ Says Woman Who Has Apparently Never Seen Sonic The Hedgehog Cosplay", url = "https://local.theonion.com/nothing-is-more-attractive-than-confidence-says-woma-1825465584", source = TheOnion }
        , { title = "‘No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1823016659", source = TheOnion }
        , { title = "I Won't Have My Daughter Bringing A Black Man Into This House Until I've Tidied Up And Created A Welcoming Environment", url = "https://www.theonion.com/i-wont-have-my-daughter-bringing-a-black-man-into-this-1819584636", source = TheOnion }
        , { title = "Trump Claims Responsibility For Longest Black History Month In 4 Years", url = "https://politics.theonion.com/trump-claims-responsibility-for-longest-black-history-m-1841991793", source = TheOnion }
        , { title = "‘No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1823016659", source = TheOnion }
        , { title = "‘The Onion’ Proudly Stands With The Media As The Enemy Of The People", url = "https://www.theonion.com/the-onion-proudly-stands-with-the-media-as-the-enemy-1828068740?utm_medium=SocialMarketing&utm_content=Main&utm_source=Twitter&utm_campaign=SF", source = TheOnion }
        , { title = "‘Paw Patrol’ Writers Defend Episode Where German Shepherd Cop Shoots Unarmed Black Lab 17 Times In Back", url = "https://entertainment.theonion.com/paw-patrol-writers-defend-episode-where-german-shephe-1828419524", source = TheOnion }
        , { title = "Going Too Far?: Nintendo Has Responded To Complaints That Marth Is Too Overpowered In ‘Smash’ By Giving Him Fibromyalgia", url = "https://ogn.theonion.com/going-too-far-nintendo-has-responded-to-complaints-th-1837812557", source = TheOnion }
        , { title = "Catholic Church Not About To Be Out-Molested By Goddamn Boy Scouts", url = "https://www.theonion.com/catholic-church-not-about-to-be-out-molested-by-goddamn-1836702707", source = TheOnion }
        , { title = "Mom Wants To Know If You Could Use Grandma’s Antique, 12-Person Dining Room Table In Your Studio Apartment", url = "https://local.theonion.com/mom-wants-to-know-if-you-could-use-grandma-s-antique-1-1831765783", source = TheOnion }
        , { title = "Inconsolable Jeff Sessions Tries To Commit Suicide By Smoking Joint", url = "https://politics.theonion.com/inconsolable-jeff-sessions-tries-to-commit-suicide-by-s-1826462420?utm_source=Twitter&utm_medium=SocialMarketing&utm_content=Main&utm_campaign=SF", source = TheOnion }
        , { title = "Marco Rubio Still Rock-Hard Days After Being Publicly Humiliated On National Stage", url = "https://politics.theonion.com/marco-rubio-still-rock-hard-days-after-being-publicly-h-1823273762", source = TheOnion }
        , { title = "Mother Feels A Little Validated After Daughter Who Stayed Out Late Gets Murdered", url = "https://local.theonion.com/mother-feels-a-little-validated-after-daughter-who-stay-1830473852?utm_content=Main&utm_source=Twitter&utm_campaign=SF&utm_medium=SocialMarketing", source = TheOnion }
        , { title = "‘No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1823016659", source = TheOnion }
        , { title = "Man Playing ‘Battlefield V’ Has Now Spent More Of Life Fighting Nazis Than Grandfather Did", url = "https://www.theonion.com/man-playing-battlefield-v-has-now-spent-more-of-life-1833231560", source = TheOnion }
        , { title = "‘I Don’t Fit Into Any Of Corporate America’s Little Boxes,’ Says Single, 18-To-36-Year-Old Hispanic Female With Brand Loyalty To Tom’s, Chobani", url = "https://www.theonion.com/i-don-t-fit-into-any-of-corporate-america-s-little-box-1824207087", source = TheOnion }
        , { title = "‘Someone In This Room Tonight Will Be Murdered By An Illegal Immigrant,’ Announces Trump Just Before Lights Go Out", url = "https://politics.theonion.com/someone-in-this-room-tonight-will-be-murdered-by-an-il-1832370781", source = TheOnion }
        , { title = "Study reveals lobsters feel pain and get off on it like the kinky little perverts they are", url = "https://www.theonion.com/study-reveals-lobsters-feel-pain-and-get-off-on-it-like-1822237552?utm_content=Main&utm_campaign=SF&utm_source=Twitter&utm_medium=SocialMarketing", source = TheOnion }
        , { title = "'No way to prevent this' says only nation where this regularly happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1823016659", source = TheOnion }
        , { title = "Paralyzed Mike Pence Lies Against Bathroom Wall For Hours After Encountering Doorknob That Looks Like Female Breast", url = "https://politics.theonion.com/paralyzed-mike-pence-lies-against-bathroom-wall-for-hou-1839861239", source = TheOnion }
        , { title = "Golden Retriever Mauls 5 In Huge Victory For Pitbull Apologists", url = "https://local.theonion.com/golden-retriever-mauls-5-in-huge-victory-for-pitbull-ap-1825397926", source = TheOnion }
        , { title = "New Stardew Valley Expansion Allows Player To Shoot Self In Barn After Family Farm Bankrupted By Corporate Agribusiness", url = "https://entertainment.theonion.com/new-stardew-valley-expansion-allows-player-to-shoot-sel-1828255833?utm_campaign=SF&utm_medium=SocialMarketing&utm_content=Main&utm_source=Twitter", source = TheOnion }
        , { title = "U.S. Flag Recalled After Causing 143 Million Deaths", url = "https://politics.theonion.com/u-s-flag-recalled-after-causing-143-million-deaths-1819571445?amp-piM84qW-eaSe4rFj0NONCw4f4NKv98Vo1R-1LfRcO_odHcOiVaKUZ0nEZHw5wMMR", source = TheOnion }
        , { title = "So-Called ‘Atheist’ Doesn’t Even Barge Into Churches Screaming ‘You’re All Brainwashed Fools’", url = "https://local.theonion.com/so-called-atheist-doesn-t-even-barge-into-churches-sc-1832871599", source = TheOnion }
        , { title = "Blood-Soaked Mayor Bloomberg Announces Homelessness No Longer A Problem In New York City", url = "https://www.theonion.com/blood-soaked-mayor-bloomberg-announces-homelessness-no-1819575714", source = TheOnion }
        , { title = "‘They Can’t Arrest Both Of Us,’ Says Giuliani Handcuffing Himself To Times Square Pikachu", url = "https://politics.theonion.com/they-can-t-arrest-both-of-us-says-giuliani-handcuffi-1838947437", source = TheOnion }
        , { title = "‘No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1819576527", source = TheOnion }
        , { title = "‘Are You The Whistleblower?’ Trump Boys Ask White House Janitor After Giving Him Serum Of All The Sodas Mixed Together", url = "https://politics.theonion.com/are-you-the-whistleblower-trump-boys-ask-white-house-1838701775", source = TheOnion }
        , { title = "‘Sorry About The Tornado Or Whatever,’ Says Trump Wolfing Down Bowl Of Chili While Consoling El Paso Shooting Victim", url = "https://politics.theonion.com/sorry-about-the-tornado-or-whatever-says-trump-wolfi-1837074904", source = TheOnion }
        , { title = "Christian Pornographer Refuses To Film Sex Tape For Gay Couple", url = "https://local.theonion.com/christian-pornographer-refuses-to-film-sex-tape-for-gay-1828084176", source = TheOnion }
        , { title = "Fox News Struggling To Attract Younger 60-75 Demographic", url = "https://www.theonion.com/fox-news-struggling-to-attract-younger-60-75-demographi-1820392371", source = TheOnion }
        , { title = "27-Year-Old Lies About Every Single Aspect Of His Life To Keep Parents From Worrying", url = "https://local.theonion.com/27-year-old-lies-about-every-single-aspect-of-his-life-1819575793", source = TheOnion }
        , { title = "Man Worried New ‘Jumanji’ Movie Going To Ruin Memory Of Mediocre Afternoon In 1995", url = "https://local.theonion.com/man-worried-new-jumanji-movie-going-to-ruin-memory-of-1821427104", source = TheOnion }
        , { title = "Third-Grader Watching Another Year Of Back To School Commercials Suddenly Realizes He’ll Die One Day", url = "https://local.theonion.com/third-grader-watching-another-year-of-back-to-school-co-1828577126", source = TheOnion }
        , { title = "Elon Musk Offering $1.2 Billion In Grants To Any Project That Promises To Make Him Feel Complete", url = "https://www.theonion.com/elon-musk-offering-1-2-billion-in-grants-to-any-projec-1822808899", source = TheOnion }
        , { title = "School Shooter Thankfully Stopped Before Doing Enough Damage To Restart National Gun Debate", url = "https://local.theonion.com/school-shooter-thankfully-stopped-before-doing-enough-d-1838201037", source = TheOnion }
        , { title = "“ We Must Protect The Pure Aryan Bloodline” Says Child After 9 Minutes of Unsupervised Facebook Access.", url = "https://local.theonion.com/we-must-protect-the-pure-aryan-bloodline-says-child-1826868946", source = TheOnion }
        , { title = "Chinese Factory Workers Fear They May Never Be Replaced With Machines", url = "https://www.theonion.com/chinese-factory-workers-fear-they-may-never-be-replaced-1819576273?utm_medium=SocialMarketing&utm_source=Twitter&utm_content=Main&utm_campaign=SF", source = TheOnion }
        , { title = "Serial Killer Admits He’s Lost Track Of Pattern He Was Going For Originally", url = "https://www.theonion.com/serial-killer-admits-he-s-lost-track-of-pattern-he-was-1819577930?utm_medium=SocialMarketing&utm_campaign=SF&utm_source=Twitter&utm_content=Main", source = TheOnion }
        , { title = "Biden Wondering Where All This Support Was When He Still Had Functioning Brain", url = "https://politics.theonion.com/biden-wondering-where-all-this-support-was-when-he-stil-1842124077", source = TheOnion }
        , { title = "Dog Who Successfully Detected Cancer In Owner Put Down For Practicing Medicine Without A License", url = "https://local.theonion.com/dog-who-successfully-detected-cancer-in-owner-put-down-1830913650", source = TheOnion }
        , { title = "42 Million Dead In Bloodiest Black Friday Weekend On Record", url = "https://www.theonion.com/42-million-dead-in-bloodiest-black-friday-weekend-on-re-1819574242", source = TheOnion }
        , { title = "Man Too Deep Into Sentence To Avoid Saying Word He Can’t Pronounce", url = "https://local.theonion.com/man-too-deep-into-sentence-to-avoid-saying-word-he-can-1819577364?utm_medium=SocialMarketing&utm_content=Main&utm_source=Twitter&utm_campaign=SF", source = TheOnion }
        , { title = "This Child Would Have Turned 6 Today If His Mother Hadn't Given Birth To Him In October", url = "https://www.theonion.com/this-child-would-have-turned-6-today-if-his-mother-hadn-1825234669", source = TheOnion }
        , { title = "‘No Way To Prevent This,’ Says Only Nation Where This Regularly Happens", url = "https://www.theonion.com/no-way-to-prevent-this-says-only-nation-where-this-r-1835173950", source = TheOnion }
        , { title = "‘Oh God, What Happened Last Night?’ Says Groggy Mike Pence After Waking Up In Same Bed As Wife", url = "https://politics.theonion.com/oh-god-what-happened-last-night-says-groggy-mike-pe-1823070030", source = TheOnion }
        , { title = "Stupid 16-Year-Old Completely Wasting Adderall Prescription On Mental Health", url = "https://local.theonion.com/stupid-16-year-old-completely-wasting-adderall-prescrip-1819577948?utm_source=Twitter&utm_medium=SocialMarketing&utm_content=Main&utm_campaign=SF", source = TheOnion }
        , { title = "Trump Honors Brave Heroes Who Slept With Wives Of Deployed Soldiers", url = "https://politics.theonion.com/trump-honors-brave-heroes-who-slept-with-wives-of-deplo-1836308926", source = TheOnion }
        , { title = "Man Pissed After Becoming Trapped In Macy’s Thanksgiving Day Parade While Out Walking Giant Pikachu Balloon", url = "https://local.theonion.com/man-pissed-after-becoming-trapped-in-macy-s-day-parade-1830597556", source = TheOnion }
        , { title = "Trump Locked Out Of White House After Accidentally Revoking Own Security Clearance", url = "https://politics.theonion.com/trump-locked-out-of-white-house-after-accidentally-revo-1828394207", source = TheOnion }
        , { title = "John Bolton Urges War Against The Sun After Uncovering Evidence It Has Nuclear Capabilities", url = "https://politics.theonion.com/john-bolton-urges-war-against-the-sun-after-uncovering-1835805360", source = TheOnion }
        , { title = "Gates Foundation Pledges $25 Billion To Eradicate Whatever Disease Drives People To Support Taxing The Rich", url = "https://www.theonion.com/gates-foundation-pledges-25-billion-to-eradicate-whate-1839699989", source = TheOnion }
        , { title = "‘Seek Funding’ Step Added To Scientific Method", url = "https://www.theonion.com/seek-funding-step-added-to-scientific-method-1819578417?utm_source=Twitter&utm_content=Main&utm_campaign=SF&utm_medium=SocialMarketing", source = TheOnion }
        , { title = "Law School Applications Increase Upon Realization That Any Fucking Idiot Can Be Lawyer", url = "https://www.theonion.com/law-school-applications-increase-upon-realization-that-1828464779", source = TheOnion }
        , { title = "Mariana Trench Once Agian Named Worst Place To Raise A Child", url = "https://www.theonion.com/mariana-trench-once-again-named-worst-place-to-raise-ch-1819575833", source = TheOnion }
        , { title = "Soldier Excited To Take Over Father’s Old Afghanistan Patrol Route", url = "https://local.theonion.com/soldier-excited-to-take-over-father-s-old-afghanistan-p-1819580201", source = TheOnion }
        , { title = "CBS Reveals ‘Big Bang Theory’ Season 12 Will Explore Why Sheldon Keeps Job After Sexually Harassing 6 Research Assistants", url = "https://entertainment.theonion.com/cbs-reveals-big-bang-theory-season-12-will-explore-wh-1827981538?utm_content=Main&utm_medium=SocialMarketing&utm_source=Twitter&utm_campaign=SF", source = TheOnion }
        , { title = "NBA Quietly Waiting For NFL To Fuck Up And Take Some Heat Off", url = "https://sports.theonion.com/nba-quietly-waiting-for-nfl-to-fuck-up-and-take-some-he-1839067266", source = TheOnion }
        , { title = "Kavanaugh Sobering Up After 35-Year Bender Shocked To Find Out He’s Supreme Court Nominee", url = "https://politics.theonion.com/kavanaugh-sobering-up-after-35-year-bender-shocked-to-f-1829331031", source = TheOnion }
        , { title = "CDC Recommends Also Wearing Face Mask On Back Of Head In Case Coronavirus Attacks From Rear", url = "https://www.theonion.com/cdc-recommends-also-wearing-face-mask-on-back-of-head-i-1841669382", source = TheOnion }
        , { title = "Shocked Vladimir Putin Slowly Realizing He Didn’t Conspire With Trump Campaign", url = "https://politics.theonion.com/shocked-vladimir-putin-slowly-realizing-he-didn-t-consp-1833575011", source = TheOnion }
        , { title = "'The Witcher’ Producers Assure Gamers Netflix Series Will Include All 400 Side Quests From ‘Wild Hunt’", url = "https://ogn.theonion.com/the-witcher-producers-assure-gamers-netflix-series-wi-1839499728", source = TheOnion }
        , { title = "Bethesda E3 Presentation Reveals They Worked Really Hard On ‘Fallout 76’ So Maybe Everyone Should Stop Being Mean Give It Another Shot", url = "https://ogn.theonion.com/bethesda-e3-presentation-reveals-they-worked-really-har-1835338164", source = TheOnion }
        , { title = "Wedding Experts Say Engagement Ring Should Cost At Least Three Diamond Miners’ Lives", url = "https://www.theonion.com/wedding-experts-say-engagement-ring-should-cost-at-leas-1834915832", source = TheOnion }
        , { title = "Man At Airport Pissed That Other People Had Same Idea To Go Home For Thanksgiving", url = "https://local.theonion.com/man-at-airport-pissed-that-other-people-had-same-idea-t-1819577256?utm_content=Main&utm_medium=SocialMarketing&utm_campaign=SF&utm_source=Twitter&__twitter_impression=true", source = TheOnion }
        , { title = "‘So People Could Be Listening To This Conversation Right Now?’ Asks Joe Rogan Trying To Understand Edward Snowden’s Explanation Of Surveillance", url = "https://www.theonion.com/so-people-could-be-listening-to-this-conversation-righ-1839294594", source = TheOnion }
        , { title = "Nation Perplexed By 16-Year-Old Who Doesn’t Want World To End", url = "https://www.theonion.com/nation-perplexed-by-16-year-old-who-doesn-t-want-world-1838374925", source = TheOnion }
        , { title = "Teen Boys Losing Virginity Earlier And Earlier, Report Teen Boys", url = "https://www.theonion.com/teen-boys-losing-virginity-earlier-and-earlier-report-1819595647", source = TheOnion }
        , { title = "Louisiana eye doctor offers free eye exams for NFL referees after Saints loss", url = "https://www.wwltv.com/article/sports/nfl/saints/louisiana-eye-doctor-offers-free-eye-exams-for-nfl-referees-after-saints-loss/289-e2f3c314-1268-4708-8b5a-5ea445099589", source = NotTheOnion }
        , { title = "Man rescued from Taliban didn't believe Donald Trump was President", url = "http://www.newsweek.com/man-rescued-taliban-didnt-believe-trump-was-president-685861", source = NotTheOnion }
        , { title = "Nat Geo hires Jeff Goldblum to walk around, being professionally fascinated by things", url = "https://news.avclub.com/nat-geo-hires-jeff-goldblum-to-walk-around-being-profe-1827880447", source = NotTheOnion }
        , { title = "Black security guard who stops shooter is then shot and killed by police", url = "https://thehill.com/homenews/news/416255-black-security-guard-stops-shooter-then-is-shot-by-police-while-holding?fbclid=IwAR272RpyOKecaxjCi0ec0aIMm8q7bsoUl7EoeYnhjBqXM0hg7hcLvWfmyCY", source = NotTheOnion }
        , { title = "Hunter dies after shot elephant falls on him", url = "http://www.news24.com/SouthAfrica/News/hunter-dies-after-shot-elephant-falls-on-him-20170521?", source = NotTheOnion }
        , { title = "People no longer believe working hard will lead to a better life, survey shows", url = "https://www.abc.net.au/triplej/programs/hack/2020-edelman-trust-barometer-shows-growing-sense-of-inequality/11883788?fbclid=IwAR09iusXpbCQ6BM5Fmsk4MVBN3OWIk2L5E8UbQKFwjg6nWpLHKgMGP2UTfM", source = NotTheOnion }
        , { title = "Mike Pence Once Ratted Out His Fraternity Brothers For Having a Keg", url = "http://www.newsweek.com/mike-pence-once-ratted-out-his-fraternity-brothers-having-keg-735711", source = NotTheOnion }
        , { title = "Reddit CEO tells user, “we are not the thought police,” then suspends that user", url = "https://arstechnica.com/information-technology/2018/07/reddit-ceo-tells-user-we-are-not-the-thought-police-then-suspends-that-user/", source = NotTheOnion }
        , { title = "R.I.P. astronaut John Young, the first man to get yelled at for smuggling a sandwich into space", url = "https://www.avclub.com/r-i-p-astronaut-john-young-the-first-man-to-get-yelle-1821845571", source = NotTheOnion }
        , { title = "Trump dedicates golf trophy to hurricane victims", url = "http://thehill.com/homenews/administration/353355-trump-dedicates-golf-trophy-to-puerto-rico-hurricane-victims", source = NotTheOnion }
        , { title = "Hipster whines at tech mag for using his pic to imply hipsters look the same, discovers pic was of an entirely different hipster", url = "https://www.theregister.co.uk/2019/03/06/hipsters_all_look_the_same_fact/", source = NotTheOnion }
        , { title = "President Trump: I would have run into school during shooting ‘even if I didn’t have a weapon’", url = "http://www.tampabay.com/florida-politics/buzz/2018/02/26/president-trump-i-would-have-run-into-school-during-shooting-even-if-i-didnt-have-a-weapon/", source = NotTheOnion }
        , { title = "Ben Affleck finally achieves lifelong dream of not having to play Batman anymore", url = "https://news.avclub.com/ben-affleck-finally-achieves-lifelong-dream-of-not-havi-1832214950", source = NotTheOnion }
        , { title = "35 Y.O CEO Slams Other Millennials For Entitlement Despite Being Handed CEO Job By His Dad", url = "https://www.pedestrian.tv/news/john-winning-privilege/", source = NotTheOnion }
        , { title = "Baby boomers are more sensitive than millennials, according to the largest-ever study on narcissism", url = "https://www.insider.com/baby-boomers-are-more-sensitive-than-millennials-large-study-finds-2019-12", source = NotTheOnion }
        , { title = "Man who ate $120,000 art banana said he would've done it sooner, but wasn't hungry yet", url = "https://www.nbcnews.com/news/us-news/man-who-ate-120-000-art-banana-said-he-would-n1098391", source = NotTheOnion }
        , { title = "EA: They’re not loot boxes, they’re “surprise mechanics,” and they’re “quite ethical”", url = "https://www.pcgamesn.com/ea-loot-boxes", source = NotTheOnion }
        , { title = "ICE Director: ICE Can't Be Compared To Nazis Since We're Just Following Orders", url = "https://politicsmaven.io/theintellectualist/news/ice-director-ice-can-t-be-compared-to-nazis-since-we-re-just-following-orders-gUCVH4E1CUi5Y73kZqpeNA/", source = NotTheOnion }
        , { title = "Uber’s search for a female CEO has been narrowed down to 3 men", url = "http://www.denverpost.com/2017/08/05/uber-search-female-ceo-men-finalists/", source = NotTheOnion }
        , { title = "Dogs cannot get ‘autism’, British Veterinary Association warns after ‘anti-vaxx’ movement spread to pets", url = "https://www.telegraph.co.uk/news/2018/04/25/dogs-cannot-get-autism-british-veterinary-association-warns/", source = NotTheOnion }
        , { title = "Somali Militant Group Al-Shabaab Announces Ban On Single-Use Plastic Bags", url = "https://www.pedestrian.tv/news/al-shabaab-plastic-bag-ban/", source = NotTheOnion }
        , { title = "United Nations official visiting Alabama to investigate 'great poverty and inequality'", url = "http://www.al.com/news/index.ssf/2017/12/united_nations_official_visiti.html#incart_river_home", source = NotTheOnion }
        , { title = "Woman Named Marijuana Pepsi, Who Refused To Change Her Name, Earns Her Ph.D After Completing Dissertation On Black Names", url = "https://blavity.com/woman-named-marijuana-pepsi-who-refused-to-change-her-name-earns-her-phd-after-completing-dissertation-on-black-names", source = NotTheOnion }
        , { title = "Florida House declares porn a public health risk shortly after denying assault rifle ban", url = "http://thehill.com/homenews/state-watch/374816-florida-house-votes-to-declare-porn-a-public-health-risk-within-an-hour", source = NotTheOnion }
        , { title = "Passenger turned away from two flights after wearing 10 layers of clothing to avoid luggage fee", url = "http://www.telegraph.co.uk/news/2018/01/16/passenger-turned-away-two-flights-wearing-10-layers-clothing/", source = NotTheOnion }
        , { title = "Man arrested for smoking marijuana while in court for marijuana charge", url = "https://www.cnn.com/2020/01/28/us/tennessee-man-marijuana-trnd/index.html", source = NotTheOnion }
        , { title = "Congress To Make Members Pay Out Of Pocket For Sexual Harassment Settlements", url = "https://www.npr.org/2018/12/12/676209258/congress-to-make-members-pay-out-of-pocket-for-sexual-harassment-settlements", source = NotTheOnion }
        , { title = "A YouTuber got the inflammatory right-wing commentator Katie Hopkins to fly to Prague to pick up a fake award whose initials spelled out the C-word", url = "https://www.insider.com/katie-hopkins-receives-fake-award-from-youtuber-c-word-2020-1", source = NotTheOnion }
        , { title = "Sean Spicer says Oprah Winfrey Doesn’t Have the Political Experience to be President", url = "http://www.itv.com/goodmorningbritain/news/sean-spicer-says-oprah-winfrey-doesnt-have-the-political-experience-to-be-president", source = NotTheOnion }
        , { title = "White House press secretary attacks media for accurately reporting inauguration crowds", url = "http://money.cnn.com/2017/01/21/media/sean-spicer-press-secretary-statement/index.html", source = NotTheOnion }
        , { title = "UPS loses Family’s $846K Inheritance, Offers to Refund $32 Shipping Fee", url = "http://www.newsweek.com/ups-loses-846k-inheritance-offer-refund-shipping-fee-748764", source = NotTheOnion }
        , { title = "School boy takes MICROWAVE to school to carry books after school bans bags", url = "https://www.lincolnshirelive.co.uk/news/local-news/school-boy-takes-microwave-school-2135169", source = NotTheOnion }
        , { title = "Alabama lawmaker: We shouldn't arm teachers because most are women", url = "http://www.al.com/news/index.ssf/2018/03/women_scare_of_guns.html", source = NotTheOnion }
        , { title = "Marilyn Manson Mourned On Twitter, Confusing Him For Dead Mass Murderer Charles", url = "http://www.newsweek.com/marilyn-manson-dead-charles-mass-murderer-die-717318", source = NotTheOnion }
        , { title = "Trump calls Warren 'Pocahontas' at event honoring Native American veterans", url = "http://thehill.com/homenews/administration/361990-trump-calls-warren-pocahontas-at-event-honoring-native-american", source = NotTheOnion }
        , { title = "Gay man's pay slashed so he'd be on par with 'other females in the office,' lawsuit claims", url = "https://www.nbcnews.com/feature/nbc-out/former-employee-sues-company-claiming-anti-gay-discrimination-n1082681", source = NotTheOnion }
        , { title = "Cat named after Notorious B.I.G. shot multiple times — and survives", url = "http://www.cbc.ca/news/canada/british-columbia/notorious-b-i-g-the-cat-survives-shooting-1.4415169", source = NotTheOnion }
        , { title = "No, this isn't The Onion, Yes Net Neutrality is under attack and we have less than a month to save it. Fight to save Net Neutrality today!", url = "http://www.battleforthenet.com", source = NotTheOnion }
        , { title = "Saudi Arabia declares online satire punishable offence", url = "https://www.france24.com/en/20180904-saudi-arabia-declares-online-satire-punishable-offence", source = NotTheOnion }
        , { title = "Trump Says Energy-Efficient Light Bulbs Make Him 'Look Orange,' Complains About How Expensive They Are", url = "https://www.newsweek.com/trump-energy-efficient-light-bulbs-orange-incandescent-expensive-1459081", source = NotTheOnion }
        , { title = "Catholic priest says ”pedophilia doesn't kill anyone” after barring pro-abortion lawmakers from communion", url = "https://www.newsweek.com/rhode-island-priest-abortion-ban-communion-1486470", source = NotTheOnion }
        , { title = "American parents say their children are speaking in British accent after watching too much Peppa Pig", url = "https://www.itv.com/news/2019-02-12/american-children-develop-british-accent-after-watching-peppa-pig/", source = NotTheOnion }
        , { title = "EPA Head Says He Needs to Fly First Class Because People Are Mean to Him in Coach", url = "http://time.com/5158661/scott-pruitt-first-class/", source = NotTheOnion }
        , { title = "Cards Against Humanity buys plot of land on U.S./Mexico border to block border wall", url = "http://www.khq.com/story/36844143/cards-against-humanity-buys-plot-of-land-on-usmexico-border-to-block-border-wall", source = NotTheOnion }
        , { title = "Five guys arrested after fist fight at Five Guys", url = "https://www.orlandosentinel.com/news/crime/os-ne-five-guys-fight-20190718-py2wtkmdo5e5zohhobzco7a5ce-story.html", source = NotTheOnion }
        , { title = "Apology after Japanese train departs 20 seconds early", url = "https://www.bbc.co.uk/news/amp/world-asia-42009839", source = NotTheOnion }
        , { title = "Justin Bieber banned from China in order to 'purify' nation", url = "http://www.telegraph.co.uk/music/news/controversial-justin-bieber-banned-china-order-purify-nation/", source = NotTheOnion }
        , { title = "Alcohol level in air at fraternity party registers on Breathalyzer", url = "http://6abc.com/alcohol-in-air-at-frat-party-registers-on-breathalyzer/2802898/?sf176857834=1", source = NotTheOnion }
        , { title = "Always look on the bright side of life, says CEO who raised EpiPen price by more than 400%", url = "http://www.latimes.com/business/lazarus/la-fi-lazarus-mylan-epipen-drug-prices-20180605-story.html", source = NotTheOnion }
        , { title = "Trump calls Dems who didn't clap during State of the Union 'treasonous' and 'un-American'", url = "https://www.yahoo.com/news/trump-calls-dems-didnt-clap-state-union-treasonous-un-american-210114640.html", source = NotTheOnion }
        , { title = "NPR tweets the Declaration of Independence, and people freak out about a ‘revolution’", url = "http://www.kansascity.com/news/nation-world/article159682299.html", source = NotTheOnion }
        , { title = "McDonald's worker fired for refusing to serve paramedics: 'We don't serve your kind here'", url = "https://www.newsweek.com/mcdonalds-worker-fired-paramedic-refused-service-1452268", source = NotTheOnion }
        , { title = "Missouri man must watch ‘Bambi’ monthly as part of poaching punishment, judge rules", url = "https://www.foxnews.com/great-outdoors/missouri-man-must-watch-bambi-monthly-as-part-of-poaching-punishment-judge-rules", source = NotTheOnion }
        , { title = "Melania flew to Texas to visit immigrant children wearing a jacket that says 'I really don't care, do u?'", url = "https://www.businessinsider.in/Melania-flew-to-Texas-to-visit-immigrant-children-wearing-a-jacket-that-says-I-really-dont-care-do-u/articleshow/64688477.cms", source = NotTheOnion }
        , { title = "Detroit man settles race discrimination lawsuit, then bank won't cash his check", url = "https://www.freep.com/story/news/local/michigan/detroit/2020/01/23/tcf-bank-race-discrimination-case-sauntore-thomas/4546199002/", source = NotTheOnion }
        , { title = "Man who mowed lawn with tornado behind him says he 'was keeping an eye on it.'", url = "http://www.timescolonist.com/man-who-mowed-lawn-with-tornado-behind-him-says-he-was-keeping-an-eye-on-it-1.20394290", source = NotTheOnion }
        , { title = "Michael B. Jordan buys teen a new retainer after she bit through it during his shirtless Black Panther scene", url = "https://www.avclub.com/michael-b-jordan-buys-teen-a-new-retainer-after-she-bi-1823581527", source = NotTheOnion }
        , { title = "Ferry McFerryface to be name of new Sydney ferry after public vote", url = "http://www.abc.net.au/news/2017-11-13/sydney-ferry-will-actually-be-called-ferry-mcferryface/9146446", source = NotTheOnion }
        , { title = "British politician wants death penalty for suicide bombers", url = "http://www.news.com.au/world/europe/british-politician-wants-death-penalty-for-suicide-bombers/news-story/0eec0b726cef5848baca05ed1022d2ca", source = NotTheOnion }
        , { title = "Missouri Republican Who Said ‘Hitler Was Right’ Wins State House Primary", url = "https://www.jpost.com//American-Politics/Missouri-Republican-who-said-Hitler-was-right-wins-state-House-primary-564637", source = NotTheOnion }
        , { title = "Texas Students Will Soon Learn Slavery Played a Central Role in the Civil War", url = "https://www.npr.org/2018/11/16/668557179/texas-students-will-soon-learn-slavery-played-a-central-role-in-the-civil-war", source = NotTheOnion }
        , { title = "US Republicans endorse arming toddlers on Sacha Baron Cohen show", url = "https://www.aljazeera.com/news/2018/07/republicans-endorse-arming-toddlers-sacha-baron-cohen-show-180716070900037.html", source = NotTheOnion }
        , { title = "A man harasses a woman for wearing a Puerto Rico shirt, saying it's 'un-American'", url = "https://edition.cnn.com/2018/07/10/us/illinois-puerto-rico-park-officer/index.html", source = NotTheOnion }
        , { title = "Michael Cohen paid IT firm to tweet that he was sexy", url = "https://www.theguardian.com/us-news/2019/jan/17/michael-cohen-paid-firm-tweet-sexy", source = NotTheOnion }
        , { title = "CVS rejects Purdue student's Puerto Rican ID, asks for immigration papers to buy cold medicine", url = "https://www.usatoday.com/story/news/nation/2019/11/03/cvs-asks-puerto-rican-student-immigration-papers-buy-cold-meds/4148821002/", source = NotTheOnion }
        , { title = "The number of Delta Air Lines passengers who bought tickets with NRA discount: 13", url = "http://www.wtsp.com/article/news/nation-now/the-number-of-delta-air-lines-passengers-who-bought-tickets-with-nra-discount-13/465-f3c2431b-ec3d-469e-8799-5060e998ecb2", source = NotTheOnion }
        , { title = "Alt-Right White Supremacists Claim Papa John's as Official Pizza", url = "http://www.newsweek.com/papa-john-alt-right-nazis-white-supremacists-nfl-pizza-701648", source = NotTheOnion }
        , { title = "White supremacists taking DNA tests sad to discover they’re not 100% white", url = "http://globalnews.ca/news/3680678/white-supremacists-dna-study/", source = NotTheOnion }
        , { title = "Army veteran has prosthetic legs repossessed after VA refuses to pay for them: ”Medicare did not send me to Vietnam”", url = "https://www.newsweek.com/army-veteran-has-prosthetic-legs-repossessed-after-va-refuses-pay-them-1481390", source = NotTheOnion }
        , { title = "After eating Chipotle for 500 days, an Ohio man says he's ready for something new", url = "http://katu.com/news/nation-world/after-eating-chipotle-for-500-days-an-ohio-man-says-hes-ready-for-something-new", source = NotTheOnion }
        , { title = "Weatherman Jamie Simpson Tells Viewers to Stop Complaining About Tornado Warnings Interrupting 'The Bachelorette': 'This Is Pathetic'", url = "https://www.newsweek.com/weatherman-jamie-simpson-fox-45-complaining-tornado-warnings-bachelorette-1436953", source = NotTheOnion }
        , { title = "School turns students' lunch debt over to collection agency", url = "https://www.nbc4i.com/news/u-s-world/school-turns-students-lunch-debt-over-to-collection-agency/1645349811", source = NotTheOnion }
        , { title = "‘El Chapo’ promises not to kill any jurors from upcoming federal trial", url = "http://wgntv.com/2018/01/25/el-chapo-promises-not-to-kill-any-jurors/", source = NotTheOnion }
        , { title = "Poll: Kim Jong Un has higher approval among Republicans than Pelosi", url = "http://thehill.com/homenews/house/392756-poll-kim-jong-un-has-higher-approval-among-republicans-than-pelosi", source = NotTheOnion }
        , { title = "After 4th DWI, man argues legal limit discriminates against alcoholics", url = "http://www.statesman.com/news/after-4th-dwi-man-argues-legal-limit-discriminates-against-alcoholics/7M59MPAdu5WImE2s9tTuPP/", source = NotTheOnion }
        , { title = "Since Jay-Z put out an album called 4:44, Jersey prog band 4:44 put out an album called Jay-Z", url = "http://thekey.xpn.org/2017/07/25/jay-z-444-444-jay-z/", source = NotTheOnion }
        , { title = "Palestinian judge bans divorce during Ramadan because ‘people make hasty decisions when they’re hungry’", url = "http://www.independent.co.uk/news/world/middle-east/ramadan-divorce-banned-palestinian-judge-people-hasty-decisions-hungry-smoke-cigarettes-mahmoud-al-a7761056.html", source = NotTheOnion }
        , { title = "Argentinian officers fired after claiming mice ate half a ton of missing marijuana", url = "https://www.theguardian.com/world/2018/apr/11/argentinian-police-officers-dismissed-after-claiming-mice-ate-marijuana?CMP=twt_gu", source = NotTheOnion }
        , { title = "Queen cancels Prince Andrew's 60th birthday party", url = "https://www.newshub.co.nz/home/entertainment/2019/11/queen-cancels-prince-andrew-s-60th-birthday-party.html", source = NotTheOnion }
        , { title = "Detective Pikachu cinematographer happy his CGI monstrosities less obviously awful than Sonic's", url = "https://news.avclub.com/detective-pikachu-cinematographer-happy-his-cgi-monstro-1834528912", source = NotTheOnion }
        , { title = "Harambe: Stop making memes of our dead gorilla, Cincinnati Zoo pleads", url = "http://www.independent.co.uk/life-style/gadgets-and-tech/news/harambe-memes-cincinnati-zoo-gorilla-shot-dead-rip-a7203356.html", source = NotTheOnion }
        , { title = "Jeff Sessions: Marijuana Is ”Only Slightly Less Awful” Than Heroin", url = "http://www.bostonmagazine.com/news/blog/2017/03/15/jeff-sessions-marijuana-slightly-less-awful-heroin/", source = NotTheOnion }
        , { title = "DC bars to open early for Comey hearing watch parties", url = "http://wtop.com/dc/2017/06/14136931/slide/1/", source = NotTheOnion }
        , { title = "Florida Mayor Arrested Just Weeks After Taking Over for Florida Mayor Who was Arrested", url = "https://newsbreakinglive.com/2019/03/14/florida-mayor-arrested-just-weeks-after-taking-over-for-florida-mayor-who-was-arrested/", source = NotTheOnion }
        , { title = "Cops take seized SUV for joyride; owner tracks car, locks them inside for 3 hrs", url = "https://www.hindustantimes.com/india-news/up-cops-take-joyride-in-seized-suv-owner-tracks-car-locks-it/story-BfN8q6TURpACr9OQwR7gLI.html", source = NotTheOnion }
        , { title = "Former Barney the Dinosaur actor now works as a controversial tantric sex guru", url = "http://www.telegraph.co.uk/tv/2018/01/24/former-barney-dinosaur-actor-now-works-controversial-tantric/", source = NotTheOnion }
        , { title = "Massive cow named Knickers has been deemed too large to eat", url = "https://globalnews.ca/news/4703769/cow-knickers-slaughterhouse/", source = NotTheOnion }
        , { title = "Man killed by blade-wielding rooster during illegal cockfight", url = "https://www.9news.com.au/world/india-man-killed-by-blade-wielding-rooster-during-cockfight/a7e2baa9-aa3b-443a-ac03-c7860eb7b4cb?fbclid=IwAR2GLq-j2A4uMrmzwEpcgAAk2xuOga6lMphLKVE4gvAxKS3JVNR3FYxH5QY", source = NotTheOnion }
        , { title = "Trump gets a folder full of positive news about himself twice a day", url = "https://news.vice.com/story/trump-folder-positive-news-white-house", source = NotTheOnion }
        , { title = "“An almond doesn’t lactate:” FDA to crack down on use of the word “milk”", url = "https://arstechnica.com/tech-policy/2018/07/an-almond-doesnt-lactate-fda-to-crack-down-on-use-of-the-word-milk/", source = NotTheOnion }
        , { title = "NYPD Union Sues To Stop Release Of All Bodycam Footage Because It Violates Officers’ Civil Rights", url = "https://lawandcrime.com/police/nypd-union-sues-to-stop-release-of-all-bodycam-footage-because-it-violates-officers-civil-rights/", source = NotTheOnion }
        , { title = "EU warns Turkey after it violates Greek airspace 141 times in one day", url = "https://www.euractiv.com/section/enlargement/news/eu-warns-turkey-after-it-violates-greek-airspace-141-times-in-one-day/", source = NotTheOnion }
        , { title = "Group of teen girls tries to set trap for alleged pedophile; one ends up kidnapped", url = "https://www.wtap.com/content/news/Group-of-teen-girls-tries-to-set-trap-for-alleged-pedophile-one-ends-up-kidnapped-562505861.html", source = NotTheOnion }
        , { title = "Tiananmen Square Massacre: China Says U.S. Is Violating International Law By Honoring 30th Anniversary", url = "https://www.newsweek.com/tiananmen-square-massacre-china-says-us-violating-international-law-honoring-30th-anniversary-1442014", source = NotTheOnion }
        , { title = "Texas prisons deny dentures to inmates with no teeth, claim chewing 'isn't a medical necessity'", url = "https://www.wnct.com/news/national/texas-prisons-deny-dentures-to-inmates-with-no-teeth-claim-chewing-isn-t-a-medical-necessity-/1473312082", source = NotTheOnion }
        , { title = "The man who stole a plane said he didn't need much help: 'I've played some video games'", url = "https://www.cnn.com/2018/08/11/us/seattle-stolen-plane-audio-recording/index.html", source = NotTheOnion }
        , { title = "White House blocks CNN, BBC, New York Times, LA Times from media briefing", url = "http://www.independent.co.uk/news/world/americas/white-house-blocks-news-outlets-from-media-briefing-a7598641.html", source = NotTheOnion }
        , { title = "'Nobody kill anybody': Murder-free weekend urged in Baltimore", url = "http://www.baltimoresun.com/news/maryland/baltimore-city/bs-md-ci-ceasefire-20170718-story.html", source = NotTheOnion }
        , { title = "University professor compares 'OK, boomer' to 'n-word,' students say", url = "https://www.cnn.com/2020/02/11/us/oklahoma-professor-n-word-ok-boomer/index.html", source = NotTheOnion }
        , { title = "Tobacco company Philip Morris starts life insurance firm that offers discounts to smokers who quit", url = "https://www.cnbc.com/2019/04/23/tobacco-company-philip-morris-launches-life-insurance-company-reviti.html", source = NotTheOnion }
        , { title = "Joe Biden claims to have worked on 2016 Paris climate deal with Chinese leader who died in 1997", url = "https://www.newsweek.com/joe-biden-claims-worked-2016-paris-climate-deal-chinese-leader-deng-xiaoping-died-1997-1488915", source = NotTheOnion }
        , { title = "Papa John's blames NFL, anthem protests for falling pizza sales", url = "http://www.theindychannel.com/news/national/papa-john-s-blames-nfl-anthem-protests-for-falling-pizza-sales", source = NotTheOnion }
        , { title = "Teacher Of The Year In Oklahoma Moves To Texas For The Money", url = "http://www.npr.org/sections/ed/2017/07/02/531911536/teacher-of-the-year-in-oklahoma-moves-to-texas-for-the-money", source = NotTheOnion }
        , { title = "Macaulay Culkin to legally change his middle name to Macaulay Culkin", url = "https://wgntv.com/2018/12/27/macaulay-culkin-to-legally-change-his-middle-name-to-macaulay-culkin/", source = NotTheOnion }
        , { title = "Pakistani girl who died in Texas shooting ‘wanted to experience American culture’", url = "http://indianexpress.com/article/world/pakistani-girl-who-died-in-texas-shooting-wanted-to-experience-american-culture-5185008/", source = NotTheOnion }
        , { title = "Family forced to sit on plane floor after airline allocated them seats which didn't exist, it emerges", url = "https://www.telegraph.co.uk/news/2019/01/13/family-forced-sit-plane-floor-airline-allocated-seats-didnt/", source = NotTheOnion }
        , { title = "Navy pilots request to be armed because they don't trust overweight police at military bases", url = "https://popularmilitary.com/navy-pilots-request-to-be-armed-because-they-dont-trust-overweight-police-at-military-bases/", source = NotTheOnion }
        , { title = "Michelin Star Restaurant Owner Invited Clemson Tigers To Experience 'What An Actual Celebration Dinner Should Be'", url = "https://www.newsweek.com/three-star-michelin-restaurant-ayesha-curry-clemson-tigers-dinner-1294437", source = NotTheOnion }
        , { title = "After 140 mph chase, man tells police he didn’t think their cruisers could catch his 2002 Acura", url = "https://fox59.com/2019/09/19/after-140-mph-chase-man-tells-police-he-didnt-think-their-cruisers-could-catch-his-2002-acura/", source = NotTheOnion }
        , { title = "Suspected murderer who evaded capture for 12 years by pretending to be mute loses voice from underuse", url = "http://www.telegraph.co.uk/news/2017/12/25/suspected-murderer-evaded-capture-12-years-pretending-mute-loses/", source = NotTheOnion }
        , { title = "Bill Cosby Gets Vanilla Pudding in Jail for First Meal Behind Bars", url = "https://theblast.com/bill-cosby-first-meal-jail-pudding/", source = NotTheOnion }
        , { title = "Thousands unfollow Sen. John McCain after he asks for more Twitter followers", url = "http://tucson.com/news/state-and-regional/thousands-unfollow-sen-john-mccain-after-he-asks-for-more/article_c6548042-d94b-11e7-aef2-7fa7e36b0339.html", source = NotTheOnion }
        , { title = "Iceland's president admits he went 'too far' with threat to ban pineapple pizza", url = "https://www.cbc.ca/radio/asithappens/iceland-s-president-admits-he-went-too-far-with-threat-to-ban-pineapple-pizza-1.4905000", source = NotTheOnion }
        , { title = "Texas judge interrupts jury, says God told him defendant is not guilty", url = "http://www.statesman.com/news/crime--law/texas-judge-interrupts-jury-says-god-told-him-defendant-not-guilty/ZRdGbT7xPu7lc6kMMPeWKL/", source = NotTheOnion }
        , { title = "'I don’t understand how you can be a pedophile and keep your job’: 12-year old asks NHC School Board", url = "https://www.wect.com/2020/02/05/i-dont-understand-how-you-can-be-pedophile-keep-your-job-year-old-asks-nhc-school-board/", source = NotTheOnion }
        , { title = "Speeding Arizona Congressman Claims 'Immunity' When Pulled Over; Brags to Cop He Goes Even Faster", url = "http://www.newsweek.com/speeding-arizona-congressman-claims-immunity-when-pulled-over-brags-cop-he-1022154", source = NotTheOnion }
        , { title = "The creators of the Nintendo 64 GoldenEye have officially ruled: Oddjob is cheating", url = "https://news.avclub.com/the-creators-of-the-nintendo-64-goldeneye-have-official-1828520705", source = NotTheOnion }
        , { title = "Detroit's largest demolition contractor demolishes the wrong home — again", url = "https://www.freep.com/story/news/local/michigan/detroit/2019/12/18/wrong-home-demolished-detroit-adamo-group/2685696001/", source = NotTheOnion }
        , { title = "Fox News isn’t worried about millions losing insurance since “we’re all going to die”", url = "http://newsweek.com/fox-news-president-donald-trump-health-care-republican-gop-were-all-gonna-die-629883", source = NotTheOnion }
        , { title = "Bush says Trump ‘makes me look pretty good’ by comparison: report", url = "http://thehill.com/homenews/administration/376909-bush-says-trump-makes-me-look-pretty-good-by-comparison-report", source = NotTheOnion }
        , { title = "NRA Says New Florida Law Would Take Away Rifles From '10-Year-Old Little Girls' on Their Birthdays", url = "https://www.newsweek.com/nra-says-new-florida-law-would-take-away-rifles-10-year-old-little-girls-their-birthdays-1454841", source = NotTheOnion }
        , { title = "Merriam-Webster adds ”sheeple” to dictionary, cites Apple users as an example", url = "https://vanguarddaily.com/merriam-webster-adds-sheeple-to-dictionary-cites-apple-users-as-an-example/", source = NotTheOnion }
        , { title = "'We want sauce': police called after McDonald's Rick and Morty promotion heats up", url = "https://www.theguardian.com/business/2017/oct/08/police-called-after-mcdonalds-rick-and-morty-promotion-heats-up?CMP=fb_gu", source = NotTheOnion }
        , { title = "R. Kelly's lawyer is complaining that the singer can visit with only one of his girlfriends at a time", url = "https://edition.cnn.com/2019/10/01/us/r-kelly-girlfriends-jail-visits/index.html", source = NotTheOnion }
        , { title = "‘They can't stop all of us': More than 250K pledge to storm Area 51 to uncover alien secrets", url = "http://www.fox10phoenix.com/news/us-world-news/they-cant-stop-all-of-us-more-than-250k-pledge-to-storm-area-51-to-uncover-alien-secrets", source = NotTheOnion }
        , { title = "Anti-vaccine advocates appointed to Minnesota autism council after measles outbreak", url = "https://arstechnica.com/science/2019/01/anti-vaccine-advocates-appointed-to-minnesota-autism-council-after-measles-outbreak/", source = NotTheOnion }
        , { title = "France Is Running Out of Butter for Its Croissants", url = "https://www.bloomberg.com/news/articles/2017-10-30/french-butter-melts-away-from-shelves-as-global-demand-soars", source = NotTheOnion }
        , { title = "Metalheads with kazoos drown out Westboro Baptist Church at Virginia Capitol.", url = "https://www.virginiamercury.com/blog-va/metalheads-with-kazoos-drown-out-westboro-baptist-church-at-capitol/", source = NotTheOnion }
        , { title = "Man Found Dead In Wife’s Freezer After A Decade Left Note Saying She Didn’t Kill Him", url = "https://baltimore.cbslocal.com/2019/12/18/man-found-dead-wifes-freezer-decade-left-notarized-note-saying-she-didnt-kill-him/", source = NotTheOnion }
        , { title = "Utah teacher fired after showing students classical paintings which contained nudity", url = "https://www.ksl.com/?sid=46226253&nid=148&title=utah-teacher-fired-after-students-see-nudity-in-art", source = NotTheOnion }
        , { title = "First Lady Melania Trump Says She Is 'the Most Bullied Person in the World'", url = "http://time.com/5421671/melania-trump-most-bullied-person-world/", source = NotTheOnion }
        , { title = "American man was arrested for scamming Nigerians of over N150 million", url = "http://ekometro.com/news/american-scam-nigerians-150-million-naira/", source = NotTheOnion }
        , { title = "Police: Naked Man Arrested At Planet Fitness Cites ‘Judgment Free Zone’", url = "https://boston.cbslocal.com/2018/07/23/planet-fitness-naked-man-eric-stagno-arrest-judgment-free-zone-plaistow", source = NotTheOnion }
        , { title = "Ohio State fan in coma asked if he likes Michigan responds 'No'", url = "https://www.theguardian.com/us-news/2017/jul/16/ohio-state-coma-zach-lawrence", source = NotTheOnion }
        , { title = "Saudi Arabia accidentally prints textbook showing Yoda sitting next to the king", url = "http://www.telegraph.co.uk/news/2017/09/22/saudi-arabia-accidentally-prints-textbook-showing-yoda-sitting/?WT.mc_id=tmg_share_tw", source = NotTheOnion }
        , { title = "“Japan’s slowest roller coaster” derails, passengers don’t notice", url = "https://soranews24.com/2018/03/25/japans-slowest-roller-coaster-derails-passengers-dont-notice/", source = NotTheOnion }
        , { title = "'Even Hitler didn't sink to using chemical weapons', says Spicer of Syria attack", url = "http://www.i24news.tv/en/news/international/americas/142490-170411-even-hitler-didn-t-sink-to-using-chemical-weapons-says-spicer-of-syria-attack", source = NotTheOnion }
        , { title = "Texas woman arrested for marijuana takes mugshot, gets requests for makeup tips", url = "http://www.foxnews.com/lifestyle/2018/08/09/texas-woman-arrested-for-marijuana-takes-mugshot-gets-requests-for-makeup-tips.html", source = NotTheOnion }
        , { title = "Drunk tourist accidentally climbs mountain while trying to get back to his hotel", url = "http://www.news.com.au/travel/travel-updates/drunk-tourist-accidentally-climbs-mountain-while-trying-to-get-back-to-his-hotel/news-story/f75ff585e07e093c8c884ea73b27be47", source = NotTheOnion }
        , { title = "Instagram Influencer With 2.6m Followers Struggles To Sell 36 T-Shirts", url = "http://www.pretty52.com/news/celebrity-instagram-influencer-with-26m-followers-struggles-to-sell-36-t-shirts-20190528", source = NotTheOnion }
        , { title = "Avocado crime soars as Mexican gangs turn focus from opium to ‘green gold’", url = "https://business.financialpost.com/financial-times/avocado-crime-soars-ahead-of-super-bowl-as-mexican-gangs-hijack-truckloads-of-green-gold-heading-north", source = NotTheOnion }
        , { title = "Moray rapist who tried to cheat justice by claiming he was too fat to appear in court died of heart disease", url = "https://www.pressandjournal.co.uk/fp/news/moray/1579181/moray-rapist-who-tried-to-cheat-justice-by-claiming-he-was-too-fat-to-appear-in-court-died-of-heart-disease/", source = NotTheOnion }
        , { title = "‘Drunk’ tourist thought to be the first person to survive swim across Hoover Dam", url = "http://www.independent.ie/irish-news/news/drunk-tourist-thought-to-be-the-first-person-to-survive-swim-across-hoover-dam-36124859.html", source = NotTheOnion }
        , { title = "Judge orders Alabama not to destroy voting records in Tuesday's Senate election", url = "http://www.al.com/news/index.ssf/2017/12/judge_orders_alabama_not_to_de.html", source = NotTheOnion }
        , { title = "In final-hour order, court rules that Alabama can destroy digital voting records after all", url = "http://www.al.com/news/index.ssf/2017/12/in_final-hour_order_court_rule.html", source = NotTheOnion }
        , { title = "YouTube will soon tell you that the world isn't flat, vaccines work, and other obvious truths", url = "https://www.androidpolice.com/2019/03/08/youtube-will-soon-tell-you-that-the-world-isnt-flat-vaccines-work-and-other-obvious-truths/", source = NotTheOnion }
        , { title = "Please Don't Roast Marshmallows Over the Erupting Hawaii Volcano, USGS Warns", url = "http://time.com/5293693/kilauea-volcano-usgs-marshmallow/", source = NotTheOnion }
        , { title = "Families earning $117,000 now qualify as ”low income” in California's Bay Area", url = "https://www.cbsnews.com/news/families-earning-117000-now-qualify-as-low-income-in-californias-bay-area/?ftag=CNM-00-10aab6a&linkId=53544816", source = NotTheOnion }
        , { title = "Fox Business Host Calls Former President George W. Bush a 'Radical' Liberal", url = "https://www.newsweek.com/fox-lou-dobbs-george-bush-liberal-1111686", source = NotTheOnion }
        , { title = "Trump claims army 'took over airports' in 1775", url = "https://www.bbc.com/news/av/world-us-canada-48879825/trump-claims-army-took-over-airports-in-1775", source = NotTheOnion }
        , { title = "Kellyanne Conway suggests Barack Obama was spying on Donald Trump through a microwave", url = "http://www.independent.co.uk/news/uk/politics/kellyanne-conway-donald-trump-barack-obama-spying-through-microwave-claims-a7626826.html", source = NotTheOnion }
        , { title = "Thousands sign petition asking for fines against people who call 911 to complain about Amber Alerts", url = "https://globalnews.ca/news/5666385/petition-amber-alert-complaints/", source = NotTheOnion }
        , { title = "Sex outside of marriage may soon be legal in Utah", url = "https://www.foxnews.com/politics/fornication-in-utah-to-no-longer-be-illegal", source = NotTheOnion }
        , { title = "Jill Stein raised more money for her recount effort than she did during the election", url = "http://time.com/money/4584102/jill-stein-recount-fundraising-election-wisconsin-michigan-pennsylvania/", source = NotTheOnion }
        , { title = "TSA agents are apparently still confused as to whether the District of Columbia is in the U.S.", url = "https://www.thestar.com/news/world/2017/12/23/tsa-agents-are-apparently-still-confused-as-to-whether-the-district-of-columbia-is-in-the-us-hint-it-is.html", source = NotTheOnion }
        , { title = "Christian family who argued taxes 'against God's will' ordered to pay $2.3m bill", url = "https://www.abc.net.au/news/2019-07-17/christian-family-ordered-to-pay-2.3-million-tax-bill/11318538?pfmredir=sm", source = NotTheOnion }
        , { title = "US cop fired over deadly shooting 'rehired to get pension'", url = "https://www.bbc.co.uk/news/world-us-canada-48969432", source = NotTheOnion }
        , { title = "U.S. warns of feral hogs approaching country from Canada", url = "https://www.ctvnews.ca/world/u-s-warns-of-feral-hogs-approaching-country-from-canada-1.4587298", source = NotTheOnion }
        , { title = "FBI director James Comey admits under oath that he hates the Patriots", url = "http://www.foxsports.com/nfl/story/fbi-director-james-comey-admits-under-oath-that-he-hates-the-patriots-032017", source = NotTheOnion }
        , { title = "Robber returns money to Philly store, says it’s not enough for his kid’s transplant", url = "https://www.inquirer.com/news/philadelphia/robber-returns-money-philadelphia-kid-transplant-20190711.html", source = NotTheOnion }
        , { title = "Florida is the worst state in the nation in every way, new rankings say", url = "http://www.thenewstribune.com/news/nation-world/national/article197092569.html#fmp", source = NotTheOnion }
        , { title = "'Mary Was a Teenager.' Alabama Republican Uses Jesus to Defend Roy Moore", url = "http://time.com/5017940/roy-moore-sexual-contact-underage-jesus-defense-jim-ziegler/", source = NotTheOnion }
        , { title = "Virginia GOP delegate tries to kill own bill to remove Democratic segregationist statue after Democrats support the bill", url = "https://thehill.com/homenews/state-watch/481167-virginia-gop-delegate-tries-to-kill-own-bill-to-remove-democratic", source = NotTheOnion }
        , { title = "Hurricane victims call sex hotline after FEMA mistakenly tweets wrong number", url = "http://wgntv.com/2017/09/22/hurricane-victims-call-sex-hotline-after-fema-mistakenly-tweets-wrong-number/", source = NotTheOnion }
        , { title = "Male cat needs glucose drip after mating with five females in one night in pet hotel", url = "https://www.nzherald.co.nz/lifestyle/news/article.cfm?c_id=6&objectid=12273971", source = NotTheOnion }
        , { title = "The world's oldest living land creature is a gay tortoise named Jonathan", url = "http://www.ksbw.com/article/jonathan-gay-tortoise-oldest-living-land-creature/13069286", source = NotTheOnion }
        , { title = "Over 500 Canadian doctors protest raises, say they're being paid too much", url = "https://www.cnbc.com/2018/03/06/canadian-doctor-protest-their-own-pay-raises.html", source = NotTheOnion }
        , { title = "‘Dr. Marijuana’ suspended for indiscriminately referring thousands of patients for medical weed", url = "https://www.nj.com/essex/2019/01/dr-marijuana-suspended-for-indiscriminately-referring-thousands-of-patients-for-medical-weed.html", source = NotTheOnion }
        , { title = "Woman gets lifetime bus pass for 103rd birthday", url = "http://www.baynews9.com/content/news/baynews9/news/article.html/content/news/articles/bn9/2017/8/16/woman_gets_lifetime_.html", source = NotTheOnion }
        , { title = "Family says supermarket wouldn't write Summa Cum Laude on a cake due to profanity", url = "http://utv44.com/news/offbeat/censored-sweets-west-ashley-family-says-publix-made-a-frosting-faux-pas-with-honors-grad", source = NotTheOnion }
        , { title = "Women's cycling race forced to pause after lead rider catches men's race", url = "https://www.theguardian.com/sport/2019/mar/03/belgian-cycling-nicole-hanselmann?CMP=fb_gu&fbclid=IwAR3NfKKLlGf3c4YSMrRUHKuBPhS-2PIgqkyYJ-HbaLu_hIL3hBf2r9Tusn0", source = NotTheOnion }
        , { title = "US lost track of 1,500 immigrant children, but says it's not 'legally responsible'", url = "https://www.cnn.com/2018/05/26/politics/hhs-lost-track-1500-immigrant-children/index.html", source = NotTheOnion }
        , { title = "Texas lawmakers consider the death penalty for abortion", url = "http://www.fox5dc.com/news/texas-lawmakers-consider-the-death-penalty-for-abortion", source = NotTheOnion }
        , { title = "Amish man launches ”Uber” ride service with his horse and buggy", url = "https://abc6onyourside.com/news/nation-world/amish-man-launches-uber-ride-service-with-his-horse-and-buggy", source = NotTheOnion }
        , { title = "Candidate for Charlotte mayor puts 'white' among qualifications", url = "http://thehill.com/homenews/state-watch/349431-candidate-for-charlotte-mayor-puts-white-among-qualifications", source = NotTheOnion }
        , { title = "Florida Drug-sniffing K-9 Called Jake Overdoses While Screening Passengers Boarding EDM Party Cruise Ship", url = "https://www.newsweek.com/florida-edm-k9-jake-overdose-narcan-cruise-ship-holy-ship-festival-norwegian-1287759", source = NotTheOnion }
        , { title = "Man finds car 20 years after forgetting where he parked it", url = "http://on.irishtimes.com/4YuDq3g", source = NotTheOnion }
        , { title = "Keeping Up With The Kardashians may make viewers cold-hearted towards poor, study suggests", url = "https://www.telegraph.co.uk/science/2018/08/01/keeping-kardashians-may-make-viewers-cold-hearted-towards-poor/", source = NotTheOnion }
        , { title = "2 kids dressed as 'tall man' unable to gain admission to 'Black Panther'", url = "http://www.actionnewsjax.com/news/trending-now/2-kids-dressed-as-tall-man-unable-to-gain-admission-to-black-panther/702418998", source = NotTheOnion }
        , { title = "Quebec denies French citizen's immigration application because chapter of thesis was in English", url = "https://www.cbc.ca/news/canada/montreal/french-thesis-immigration-caq-1.5351155", source = NotTheOnion }
        , { title = "Facebook is suggesting mobile users 'Protect' themselves...by downloading a Facebook-owned app that tracks their mobile usage", url = "https://www.cnbc.com/2018/02/12/facebook-promoting-onavo-protect-without-disclosing-ownership.html", source = NotTheOnion }
        , { title = "Sheriff who pocketed $750K from inmate food fund bought beach house for $740K", url = "http://www.fox32chicago.com/news/dont-miss/sheriff-who-pocketed-750k-from-inmate-food-fund-bought-beach-house-for-740k", source = NotTheOnion }
        , { title = "'I was annoyed': Woman, 95, shoos black bear out of kitchen twice in one day", url = "https://www.ctvnews.ca/canada/i-was-annoyed-woman-95-shoos-black-bear-out-of-kitchen-twice-in-one-day-1.4037741", source = NotTheOnion }
        , { title = "Juncker used ‘brightly coloured, simple flashcards’ to explain trade to Trump during meeting", url = "https://www.independent.co.uk/news/world/americas/us-politics/trump-juncker-trade-us-eu-trade-tariffs-white-house-meeting-flashcards-a8467051.html", source = NotTheOnion }
        , { title = "Sign language interpreter used gibberish, warned of bears, monsters during Hurricane Irma update", url = "http://www.al.com/news/index.ssf/2017/09/sign_language_interpreter_used.html", source = NotTheOnion }
        , { title = "Ad stating alcohol is a drug blocked as ‘too political’", url = "https://www.irishexaminer.com/breakingnews/ireland/ad-stating-alcohol-is-a-drug-blocked-as-too-political-971955.html", source = NotTheOnion }
        , { title = "Woman tells TripAdvisor she was raped by guide, TripAdvisor tells her to leave bad review", url = "https://www.newsweek.com/tripadvisor-rape-review-woman-tour-guide-sexual-assault-1352169", source = NotTheOnion }
        , { title = "Cop Does Not Shoot Unarmed Man", url = "http://www.newhavenindependent.org/index.php/archives/entry/cop_does_not_shoot_unarmed_man/", source = NotTheOnion }
        , { title = "Man Creates Tinder-Like Dating App Where He’s the Only Guy Available", url = "http://www.menshealth.com/sex-women/guy-creates-own-tinder-app?", source = NotTheOnion }
        , { title = "Ambien-maker to Roseanne: Racism is not a side effect of our drug", url = "https://www.usatoday.com/story/news/nation-now/2018/05/30/roseanne-barr-blames-ambien-zolpidem-drug-real-side-effects/654683002/", source = NotTheOnion }
        , { title = "Alabama Won’t Air “Arthur” Cartoon With Gay Wedding", url = "https://www.nbcnews.com/feature/nbc-out/alabama-public-television-refuses-air-arthur-episode-gay-wedding-n1008026", source = NotTheOnion }
        , { title = "Senate adopts resolution declaring ”the press is not the enemy of the people”", url = "https://www.cbsnews.com/news/senate-unanimously-passes-resolution-declaring-the-press-is-not-the-enemy-of-the-people/", source = NotTheOnion }
        , { title = "Man launches GoFundMe page to ‘protect Betty White from 2016’", url = "http://www.ketv.com/article/man-launches-gofundme-page-to-protect-betty-white-from-2016/8539848", source = NotTheOnion }
        , { title = "Elderly Americans Are Dying Without Getting To Read Mueller's Report - And They're Not Happy About It", url = "https://www.newsweek.com/elderly-americans-are-dying-without-getting-read-muellers-report-and-theyre-1352933?amp=1&__twitter_impression=true", source = NotTheOnion }
        , { title = "Ex-Chipotle manager, accused of stealing $626, gets $8 million for wrongful termination", url = "http://www.foxnews.com/food-drink/2018/05/14/ex-chipotle-manager-accused-stealing-626-gets-8-million-for-wrongful-termination.amp.html", source = NotTheOnion }
        , { title = "Seagulls keep couple hostage in their own home for six days by attacking them every time they leave house", url = "https://www.telegraph.co.uk/news/2019/06/21/seagulls-keep-couple-hostage-home-six-days-attacking-every-time/", source = NotTheOnion }
        , { title = "Man checks in a can of beer as only luggage on Perth bound flight", url = "http://www.news.com.au/travel/travel-updates/man-checks-in-a-can-of-beer-as-only-luggage-on-perth-bound-flight/news-story/035e1cc62252967d2d6b6dbb106502c9", source = NotTheOnion }
        , { title = "Tom Holland’s Drunk, Crying Phone Call With Disney CEO Saved Spider-Man From MCU Exit", url = "https://www.indiewire.com/2019/12/tom-holland-drunk-phone-call-saved-spider-man-mcu-exit-1202194520/", source = NotTheOnion }
        , { title = "Cruise Ship Refunds Passengers After 1,300 Men Took Over and Turned It Into a Giant Burlesque Show", url = "https://www.newsweek.com/cruise-ship-refunds-passengers-after-1300-men-took-over-and-turned-it-giant-1148493", source = NotTheOnion }
        , { title = "Donald Trump says he doesn't need daily intelligence briefings as President because he's 'smart'", url = "http://www.independent.co.uk/news/world/americas/us-elections/donald-trump-says-hes-too-smart-for-daily-intelligence-briefings-a7468456.html", source = NotTheOnion }
        ]
